

target 'Tranb' do

  use_frameworks!

	pod "AFNetworking"
    pod "WechatOpenSDK"
    pod "WeiboSDK"
pod "SDWebImage"
pod "YYModel"
pod "FMDB"
pod "SVProgressHUD"
pod "pop"
pod 'SnapKit', '~> 3.2.0'


  target 'TranbTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TranbUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
